"""
Pydantic data models used throughout the application.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────────────────────────
# User / Candidate profile
# ─────────────────────────────────────────────────────────────────

class UserProfile(BaseModel):
    """Structured profile extracted from a CV or a freeform job-search description."""

    raw_text: str = ""

    # Personal info
    name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None

    # Professional background
    skills: List[str] = Field(default_factory=list)
    experience_years: Optional[int] = None
    current_title: Optional[str] = None
    education: List[str] = Field(default_factory=list)
    certifications: List[str] = Field(default_factory=list)
    languages: List[str] = Field(default_factory=list)  # spoken/programming languages
    summary: str = ""

    # Job preferences
    desired_titles: List[str] = Field(default_factory=list)
    desired_location: Optional[str] = None
    desired_remote: bool = False

    # Search helpers (generated by LLM or heuristics)
    keywords: List[str] = Field(default_factory=list)
    search_queries: List[str] = Field(default_factory=list)

    def to_search_text(self) -> str:
        """Return a single string that represents the candidate for semantic matching."""
        parts: List[str] = []
        if self.current_title:
            parts.append(f"Job title: {self.current_title}")
        if self.desired_titles:
            parts.append(f"Looking for: {', '.join(self.desired_titles)}")
        if self.skills:
            parts.append(f"Skills: {', '.join(self.skills[:25])}")
        if self.experience_years:
            parts.append(f"{self.experience_years} years of experience")
        if self.summary:
            parts.append(self.summary)
        if self.keywords:
            parts.append(" ".join(self.keywords[:20]))
        return " | ".join(parts) if parts else self.raw_text[:800]


# ─────────────────────────────────────────────────────────────────
# Job listing
# ─────────────────────────────────────────────────────────────────

class Job(BaseModel):
    """A job listing retrieved from any source."""

    id: str = ""
    title: str
    company: str

    location: Optional[str] = None
    remote: bool = False
    job_type: Optional[str] = None      # full-time | part-time | contract | …

    description: str = ""               # full HTML or plain text
    url: str = ""

    salary_min: Optional[float] = None
    salary_max: Optional[float] = None
    salary_currency: str = "USD"
    salary_period: Optional[str] = None  # year | month | hour

    posted_date: Optional[str] = None
    source: str = ""                    # Remotive | JSearch | Adzuna | …

    required_skills: List[str] = Field(default_factory=list)
    raw_data: Dict[str, Any] = Field(default_factory=dict)

    def to_match_text(self) -> str:
        """Return a single string that represents the job for semantic matching."""
        parts = [self.title, self.company]
        if self.location:
            parts.append(self.location)
        if self.required_skills:
            parts.append(f"Skills: {', '.join(self.required_skills)}")
        if self.description:
            parts.append(self.description[:1500])
        return " | ".join(parts)

    def get_salary_display(self) -> str:
        """Return a human-readable salary range string."""
        period = (self.salary_period or "year").lower()
        if self.salary_min and self.salary_max:
            return (
                f"{self.salary_currency} "
                f"{self.salary_min:,.0f} – {self.salary_max:,.0f} / {period}"
            )
        if self.salary_min:
            return f"{self.salary_currency} {self.salary_min:,.0f}+ / {period}"
        if self.salary_max:
            return f"{self.salary_currency} up to {self.salary_max:,.0f} / {period}"
        return "Not disclosed"


# ─────────────────────────────────────────────────────────────────
# Ranked job (job + match metadata)
# ─────────────────────────────────────────────────────────────────

class RankedJob(BaseModel):
    """A job enriched with relevance scoring metadata."""

    job: Job
    match_score: float = 0.0            # 0 – 100
    match_reasons: List[str] = Field(default_factory=list)
    matched_skills: List[str] = Field(default_factory=list)
    missing_skills: List[str] = Field(default_factory=list)

    @property
    def score_label(self) -> str:
        if self.match_score >= 80:
            return "Excellent Match"
        if self.match_score >= 60:
            return "Good Match"
        if self.match_score >= 40:
            return "Fair Match"
        return "Low Match"

    @property
    def score_color(self) -> str:
        if self.match_score >= 80:
            return "#22c55e"
        if self.match_score >= 60:
            return "#f59e0b"
        return "#ef4444"
